# GitHub Actions Workflow for Azure Functions CI/CD
# This workflow builds and deploys the Azure Function App using Bicep and Azure Functions Action

name: Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_NAME: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_LOCATION: westeurope
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build (if needed)
        run: npm run build --if-present

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure (Bicep)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --name YeaBuddyBotDeployment \
              --template-file infrastructure/main.bicep \
              --parameters functionAppName=${{ env.AZURE_FUNCTIONAPP_NAME }} storageAccountName=${{ env.AZURE_STORAGE_ACCOUNT }}

      - name: Publish to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
